name: nfgarch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - pip
  - pip:
    - torch>=1.9.0
    - torchvision>=0.10.0
    - pyyaml>=5.4.0
